// src/components/ProfileInfoComponent.vue
﻿<template>
<div class="w-full flex p-10">
  <div class="w-[100px] h-[100px] mr-10">
    <AvatarComponent :avatar="profile.Avatar" :nickname="profile.Nickname"/>
  </div>
  <div class="flex justify-between w-full">
    <div>
      <div class="flex">
        <h1 class="text-3xl font-bold h-fit">{{profile.Nickname}}</h1>
        <h4 v-if="profile.FirstName || profile.LastName" class="text-md capitalize font-semibold italic ml-2 h-fit my-auto">( {{profile.FirstName}} {{profile.LastName}} )</h4>
      </div>
      <p v-if="profile.age > 0">Age: {{profile.Age}}</p>
    </div>
    <div class="font-semibold flex flex-col justify-around">
      <p class="w-fit ml-auto mb-auto">Join date: {{profile.JoiningDate}}</p>
      <RouterLink v-if="isProfileOwner" class="uppercase font-semibold w-fit ml-auto text-gray-400" :to="'/profile/edit/' + profile.Nickname" >Edit</RouterLink>
      <div v-if="profile.DiscordNick" class="flex w-fit ml-auto mt-auto">
        <img class="h-[15px] object-contain my-auto mr-1.5" src="@/assets/images/discord-icon.png" alt="discord">
        <p>{{profile.DiscordNick}}</p>
      </div>
    </div>
    
  </div>
</div>
</template>

<script>
import AvatarComponent from "@/components/subcomponents/AvatarComponent.vue";
export default {
  name: "ProfileInfoComponent",
  components: {AvatarComponent},
  props: {
    profile: {},
    isProfileOwner: Boolean
  },
}
</script>

// src/Component/ProfileInfo.tsx
import React from "react";
import { ProfileModel } from "../types";

interface Props {
    currentUser: ProfileModel;
}

const ProfileInfo: React.FC<Props> = ({ currentUser }) => {

    return (
        <>
            <div id="profileInfo" className='flex py-10 px-10'>
                <div className='ring-4 mr-10 ring-primary rounded-full bg-primary'>
                    <img className='h-[100px] object-contain' src='/images/avatar-empty.png' alt='avatar' />
                </div>
                <div className='flex w-full relative'>

                    <div>
                        <div className='flex h-fit'>
                            <h1 className="text-3xl font-bold h-fit"> {currentUser.Nickname} </h1>
                            <h4 className="text-md capitalize font-semibold italic ml-2 h-fit my-auto">( {currentUser.FirstName} {currentUser.LastName} )</h4>
                        </div>
                        <div>
                            <p>Age: {currentUser.Age}</p>
                        </div>
                    </div>

                    <div className='ml-auto font-semibold h-fit'>
                        <div className='flex w-fit absolute bottom-0 w-38 right-0'>
                            <img className='h-[15px] object-contain my-auto mr-1.5' src='/images/discord-icon.png' alt='discord' />
                            <p>{currentUser.DiscordNick}</p>
                        </div>
                        <p className='absolute top-0 w-38 right-0'>Join date: {currentUser.JoiningDate}</p>
                    </div>

                </div>
            </div>
        </>
    )
}

export default ProfileInfo;
