// src/App.tsx
import React, { useEffect, useState } from 'react';
import Profile from './Component/Profile';
import LoginPage from './Component/LoginPage';
import './App.css';
import { useStateValue } from './state/state';
import { User, ProfileModel } from './types';
import { getUsers } from './services/userService';
import { getProfiles } from './services/profileService';
import {
  HashRouter as Router,
  Route, Link, Routes
} from "react-router-dom"
import HomePage from './Component/HomePage';
import CustomRouter from './Component/CustomRouter';




const App: React.FC = () => {
  const [{ email }, dispatch] = useStateValue();

  useEffect(() => {
    getUsers().then(user => {
      const users: User[] = user as User[];

      dispatch({ type: "GET_USERS", payload: users });
    });

    getProfiles().then(data => {

      const profiles: ProfileModel[] = data as ProfileModel[];
      dispatch({ type: "GET_PROFILES", payload: profiles });
    });

    const loggedUserJSON = window.localStorage.getItem('loggedUser');
    if (loggedUserJSON && loggedUserJSON !== undefined) {
      const user = JSON.parse(loggedUserJSON);

      dispatch({ type: "LOGIN", payload: user });
    }

  }, [dispatch]);

  if (email === "") {
    return (
      <LoginPage />
    )
  } else {

    window.localStorage.setItem(
      'loggedUser', JSON.stringify(email)
    )

    const handleLogout = () => {
      window.localStorage.clear();
      dispatch({ type: "LOGOUT", payload: "" })
    }

    return (
      <CustomRouter>
        <header>
          <nav className="h-[65px] border-b shadow-lg flex relative font-semibold text-gray-600">

            <div className="absolute w-full h-full">
              <div className="flex h-full mx-auto w-fit justify-around">
                <Link to="/"><button className="px-5 hover:bg-gray-300 h-full hover:text-gray-900">Feed</button></Link>
                <button onClick={handleLogout} className="px-5 hover:bg-gray-300 hover:text-gray-900">About</button>
              </div>
            </div>

            <div className="ml-auto flex z-10">
              <Link to="/profile"><button className="h-full px-5 hover:bg-gray-300 hover:text-gray-900">Profile</button></Link>
              <Link to="/login"><button onClick={handleLogout} className="h-full px-5 hover:bg-red-400 bg-red-600 text-white">Logout</button></Link>
            </div>

          </nav>
        </header>
        <Routes>
          <Route path='/' element={<HomePage />} />
          <Route path='/profile' element={<Profile />} />
          <Route path='/login' element={<LoginPage />} />
        </Routes>
      </CustomRouter>
    );
  }
}

export default App;

// src/App.vue
<template>
  <nav class="h-[65px] flex relative font-semibold text-gray-600 bg-white drop-shadow-lg z-20">
    
    <div class="flex h-full mx-auto w-fit justify-around">
      <router-link class="px-5 hover:bg-gray-300 h-full hover:text-gray-900" v-for="navItem in navLinks" :key="navItem.navName" :to="navItem.to"><button class="h-full">{{navItem.navName}}</button></router-link>
    </div>
    
    <div class="absolute right-0 h-[65px] flex">

      <a href="https://localhost:5001/Auth/Login">
        <button class="h-full px-5 hover:bg-gray-300 hover:text-gray-900">Login</button>
      </a>
      
      <router-link to="/profile">
        <button class="h-full px-5 hover:bg-gray-300 hover:text-gray-900 flex">
          <AvatarHelper class="h-[40px] my-auto"/>
          <span class="text-regular my-auto ml-2">Profiili</span>
        </button>
      </router-link>
      
      <a>
        <button @click="logout" class="px-5 bg-red-600 h-full text-white hover:bg-red-400">Logout</button>
      </a>
    </div>
    
  </nav>
  
  <div class="text-gray-300">
    <router-view/>
  </div>
  
</template>

<script>

import axios from "axios";
import AvatarHelper from "@/helpers/AvatarHelper";

export default {
  
  components: {AvatarHelper},
  
  data() {
    return {
      
      navLinks: [ 
        { navName: "Feed", to: "/" }, 
        { navName: "About", to: "/about" } 
      ],
      
      api : 'https://localhost:5001/',
      
    }
  },
  
}

</script>

<style scoped>
@import './assets/output.css';
</style>
